version: '3.1'
services:
  opensearch:
    image: opensearchproject/opensearch:1.2.3
    container_name: opensearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - mynetwork

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    networks:
      - mynetwork

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:7.14.0
    container_name: packetbeat
    user: root
    cap_add:
      - NET_ADMIN
    volumes:
      - ./packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    network_mode: "host"
    command: ["-e", "-strict.perms=false"]
    depends_on:
      - opensearch
  
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      GF_INSTALL_PLUGINS: "grafana-opensearch-datasource"

networks:
  mynetwork:
    driver: bridge

volumes:
  opensearch-data:
