version: '3'
services:
  opensearch:
    build:
      context: ./opensearch
      dockerfile: Dockerfile
    container_name: opensearch
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: admin
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    expose:
      - "9200"  # 다른 컨테이너가 접근
      - "9600"
    volumes:
      - ./opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro,Z
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 2g

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    networks:
      - mynetwork
    extra_hosts:
      - "opensearch:${LOCAL_IP}"
    depends_on:
      - opensearch
    deploy:
      resources:
        limits:
          memory: 1g 

  packetbeat:
    build:
      context: ./packetbeat
      dockerfile: Dockerfile
    container_name: packetbeat
    user: root
    cap_add:
      - NET_ADMIN
    volumes:
      - ./packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    network_mode: "host"
    extra_hosts:
      - "opensearch:${LOCAL_IP}"
    depends_on:
      - opensearch
  
  # grafana:
  #   image: grafana/grafana:8.0.6
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mynetwork
  #   environment:
  #     GF_INSTALL_PLUGINS: "grafana-opensearch-datasource"

  kibana:
    image: opensearchproject/opensearch-dashboards:1.3.17
    container_name: kibana
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    ports:
      - "5601:5601"
    networks:
      - mynetwork
    depends_on:
      - opensearch
    extra_hosts:
      - "opensearch:${LOCAL_IP}"
    deploy:
      resources:
        limits:
          memory: 1g

networks:
  mynetwork:
    driver: bridge

volumes:
  opensearch-data:
